default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsreact
  password: <%= ENV['HELLO_RAILS_REACT_DATABASE_PASSWORD'] %>
development:
  <<: *default
  database: Hello_rails_react_developemnt
  host: localhost
  port: 5432

test:
  <<: *default
  database: Hello_rails_react_test
  username: railsreact
  password: <%= ENV['HELLO_RAILS_REACT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: Hello-rails-react_production
  username: railsreact
  password: <%= ENV['HELLO_RAILS_REACT_DATABASE_PASSWORD'] %>
