Greeting.create(message: 'Hello, All!')
Greeting.create(message: 'Hola, Mundo!')
Greeting.create(message: 'Hey, jjsh')
Greeting.create(message: 'Hallo, there!')
Greeting.create(message: 'Great, Welt!')
